require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GemReviewsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # GemReview. As you add validations to GemReview, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GemReviewsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all gem_reviews as @gem_reviews" do
      gem_review = GemReview.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:gem_reviews)).to eq([gem_review])
    end
  end

  describe "GET show" do
    it "assigns the requested gem_review as @gem_review" do
      gem_review = GemReview.create! valid_attributes
      get :show, {:id => gem_review.to_param}, valid_session
      expect(assigns(:gem_review)).to eq(gem_review)
    end
  end

  describe "GET new" do
    it "assigns a new gem_review as @gem_review" do
      get :new, {}, valid_session
      expect(assigns(:gem_review)).to be_a_new(GemReview)
    end
  end

  describe "GET edit" do
    it "assigns the requested gem_review as @gem_review" do
      gem_review = GemReview.create! valid_attributes
      get :edit, {:id => gem_review.to_param}, valid_session
      expect(assigns(:gem_review)).to eq(gem_review)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GemReview" do
        expect {
          post :create, {:gem_review => valid_attributes}, valid_session
        }.to change(GemReview, :count).by(1)
      end

      it "assigns a newly created gem_review as @gem_review" do
        post :create, {:gem_review => valid_attributes}, valid_session
        expect(assigns(:gem_review)).to be_a(GemReview)
        expect(assigns(:gem_review)).to be_persisted
      end

      it "redirects to the created gem_review" do
        post :create, {:gem_review => valid_attributes}, valid_session
        expect(response).to redirect_to(GemReview.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gem_review as @gem_review" do
        post :create, {:gem_review => invalid_attributes}, valid_session
        expect(assigns(:gem_review)).to be_a_new(GemReview)
      end

      it "re-renders the 'new' template" do
        post :create, {:gem_review => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested gem_review" do
        gem_review = GemReview.create! valid_attributes
        put :update, {:id => gem_review.to_param, :gem_review => new_attributes}, valid_session
        gem_review.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested gem_review as @gem_review" do
        gem_review = GemReview.create! valid_attributes
        put :update, {:id => gem_review.to_param, :gem_review => valid_attributes}, valid_session
        expect(assigns(:gem_review)).to eq(gem_review)
      end

      it "redirects to the gem_review" do
        gem_review = GemReview.create! valid_attributes
        put :update, {:id => gem_review.to_param, :gem_review => valid_attributes}, valid_session
        expect(response).to redirect_to(gem_review)
      end
    end

    describe "with invalid params" do
      it "assigns the gem_review as @gem_review" do
        gem_review = GemReview.create! valid_attributes
        put :update, {:id => gem_review.to_param, :gem_review => invalid_attributes}, valid_session
        expect(assigns(:gem_review)).to eq(gem_review)
      end

      it "re-renders the 'edit' template" do
        gem_review = GemReview.create! valid_attributes
        put :update, {:id => gem_review.to_param, :gem_review => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gem_review" do
      gem_review = GemReview.create! valid_attributes
      expect {
        delete :destroy, {:id => gem_review.to_param}, valid_session
      }.to change(GemReview, :count).by(-1)
    end

    it "redirects to the gem_reviews list" do
      gem_review = GemReview.create! valid_attributes
      delete :destroy, {:id => gem_review.to_param}, valid_session
      expect(response).to redirect_to(gem_reviews_url)
    end
  end

end
